
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ClientSessionProvider from "@/components/clientsessionprovider";
// import { SessionProvider } from 'next-auth/react';
// import '../styles/globals.scss';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,session
}: Readonly<{
  children: React.ReactNode,
  session:any
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <ClientSessionProvider session={session}>
        {children}
        
      </ClientSessionProvider>
      </body>
    </html>
  );
}
  